/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as CozinhaRouteImport } from './routes/cozinha'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosTableIdRouteImport } from './routes/pedidos.$tableId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaRoute = CozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosTableIdRoute = PedidosTableIdRouteImport.update({
  id: '/pedidos/$tableId',
  path: '/pedidos/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/cozinha': typeof CozinhaRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/pedidos/$tableId': typeof PedidosTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/cozinha': typeof CozinhaRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/pedidos/$tableId': typeof PedidosTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caixa': typeof CaixaRoute
  '/cardapio': typeof CardapioRoute
  '/cozinha': typeof CozinhaRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/pedidos/$tableId': typeof PedidosTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/caixa'
    | '/cardapio'
    | '/cozinha'
    | '/historico'
    | '/login'
    | '/pedidos/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/caixa'
    | '/cardapio'
    | '/cozinha'
    | '/historico'
    | '/login'
    | '/pedidos/$tableId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/caixa'
    | '/cardapio'
    | '/cozinha'
    | '/historico'
    | '/login'
    | '/pedidos/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CaixaRoute: typeof CaixaRoute
  CardapioRoute: typeof CardapioRoute
  CozinhaRoute: typeof CozinhaRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  PedidosTableIdRoute: typeof PedidosTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha': {
      id: '/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof CozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$tableId': {
      id: '/pedidos/$tableId'
      path: '/pedidos/$tableId'
      fullPath: '/pedidos/$tableId'
      preLoaderRoute: typeof PedidosTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CaixaRoute: CaixaRoute,
  CardapioRoute: CardapioRoute,
  CozinhaRoute: CozinhaRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  PedidosTableIdRoute: PedidosTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
